config/routes.rb
Rails.application.routes.draw do

  resources :image_descriptions
  resources :images
  resources :categories

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_one :image_descriptions
  belongs_to :categories

end

app/models/image_description.rb
class ImageDescription < ActiveRecord::Base
  belongs_to :images
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  before_filter :authorize

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:label, :date_creation)
    end
end

app/controllers/image_descriptions_controller.rb
class ImageDescriptionsController < ApplicationController
  before_action :set_image_description, only: [:show, :edit, :update, :destroy]

  # GET /image_descriptions
  # GET /image_descriptions.json
  def index
    @image_descriptions = ImageDescription.all
  end

  # GET /image_descriptions/1
  # GET /image_descriptions/1.json
  def show
  end

  # GET /image_descriptions/new
  def new
    @image_description = ImageDescription.new
  end

  # GET /image_descriptions/1/edit
  def edit
  end

  # POST /image_descriptions
  # POST /image_descriptions.json
  def create
    @image_description = ImageDescription.new(image_description_params)

    respond_to do |format|
      if @image_description.save
        format.html { redirect_to @image_description, notice: 'Image description was successfully created.' }
        format.json { render :show, status: :created, location: @image_description }
      else
        format.html { render :new }
        format.json { render json: @image_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_descriptions/1
  # PATCH/PUT /image_descriptions/1.json
  def update
    respond_to do |format|
      if @image_description.update(image_description_params)
        format.html { redirect_to @image_description, notice: 'Image description was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_description }
      else
        format.html { render :edit }
        format.json { render json: @image_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_descriptions/1
  # DELETE /image_descriptions/1.json
  def destroy
    @image_description.destroy
    respond_to do |format|
      format.html { redirect_to image_descriptions_url, notice: 'Image description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_description
      @image_description = ImageDescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_description_params
      params.require(:image_description).permit(:title, :description, :width, :height)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:url, :date_creation, :visible, :deleted, :date_deleted, :category_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_login(params[:login])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url, notice: "Logged in!"
    else
      flash.now.alert = "Login or password is invalid."
    end
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/image_descriptions_helper.rb
module ImageDescriptionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Administration</h1>

<ul>
  <li><%= link_to 'Manage Users' %></li>
  <li><%= link_to 'Manage Articles' %></li>
</ul>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :date_creation %><br>
    <%= f.datetime_select :date_creation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Date creation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.label %></td>
        <td><%= category.date_creation %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @category.label %>
</p>

<p>
  <strong>Date creation:</strong>
  <%= @category.date_creation %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/image_descriptions/_form.html.erb
<%= form_for(@image_description) do |f| %>
  <% if @image_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_description.errors.count, "error") %> prohibited this image_description from being saved:</h2>

      <ul>
      <% @image_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_descriptions/edit.html.erb
<h1>Editing Image Description</h1>

<%= render 'form' %>

<%= link_to 'Show', @image_description %> |
<%= link_to 'Back', image_descriptions_path %>

app/views/image_descriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Image Descriptions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Width</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_descriptions.each do |image_description| %>
      <tr>
        <td><%= image_description.title %></td>
        <td><%= image_description.description %></td>
        <td><%= image_description.width %></td>
        <td><%= image_description.height %></td>
        <td><%= link_to 'Show', image_description %></td>
        <td><%= link_to 'Edit', edit_image_description_path(image_description) %></td>
        <td><%= link_to 'Destroy', image_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image description', new_image_description_path %>

app/views/image_descriptions/new.html.erb
<h1>New Image Description</h1>

<%= render 'form' %>

<%= link_to 'Back', image_descriptions_path %>

app/views/image_descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image_description.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @image_description.description %>
</p>

<p>
  <strong>Width:</strong>
  <%= @image_description.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @image_description.height %>
</p>

<%= link_to 'Edit', edit_image_description_path(@image_description) %> |
<%= link_to 'Back', image_descriptions_path %>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :date_creation %><br>
    <%= f.datetime_select :date_creation %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.check_box :deleted %>
  </div>
  <div class="field">
    <%= f.label :date_deleted %><br>
    <%= f.datetime_select :date_deleted %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Date creation</th>
      <th>Visible</th>
      <th>Deleted</th>
      <th>Date deleted</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.url %></td>
        <td><%= image.date_creation %></td>
        <td><%= image.visible %></td>
        <td><%= image.deleted %></td>
        <td><%= image.date_deleted %></td>
        <td><%= image.category_id %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @image.url %>
</p>

<p>
  <strong>Date creation:</strong>
  <%= @image.date_creation %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @image.visible %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @image.deleted %>
</p>

<p>
  <strong>Date deleted:</strong>
  <%= @image.date_deleted %>
</p>

<p>
  <strong>Category:</strong>
  <%= @image.category_id %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>